apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}-fe
  name: {{ .Chart.Name }}-fe
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-fe
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-fe
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 30080
          env:
            - name: REACT_APP_APIHOSTPORT
              value: "{{ .Values.EnvVariables.REACT_APP_APIHOSTPORT }}"
