apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}-fe
  name: {{ .Values.frontend.service.name }}
spec:
  ports:
    - port: {{ .Values.frontend.service.port }}
      protocol: TCP
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    app: {{ .Chart.Name }}-fe
  type: {{ .Values.frontend.service.type }}

