apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}-be
  name: {{ .Values.backend.serviceNodePort.name }} 
spec:
  ports:
    - port: {{ .Values.backend.serviceNodePort.port }}
      protocol: TCP
      targetPort: {{ .Values.backend.serviceNodePort.targetPort }}
      nodePort: {{ .Values.backend.serviceNodePort.nodePort }}
  selector: 
    app: {{ .Chart.Name }}-be
  type: {{ .Values.backend.serviceNodePort.type }}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}-be
  name: {{ .Values.backend.serviceClusterIP.name }}
spec:
  type: {{ .Values.backend.serviceClusterIP.type }}
  ports:
    - port: {{ .Values.backend.serviceClusterIP.port }}
      protocol: TCP
      targetPort: {{ .Values.backend.serviceClusterIP.targetPort }}
  clusterIP: {{ .Values.backend.serviceClusterIP.clusterIP }}
  selector:
    app: {{ .Chart.Name }}-be
