apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-backend-pipeline-run-
spec:
  pipelineRef:
    name: ci-backend-pipeline
  params:
    - name: repo-url
      value: "https://github.com/hjk08/Semstralna_praca_ONPK.git"
    - name: image-reference
      value: "hjk08/backend:latest"
    - name: dockerfile
      value: "docker/zauni-zadanie-appbackend/Dockerfile"
    - name: context
      value: "docker/zauni-zadanie-appbackend"
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: docker-credentials
